events {
    multi_accept on;
    worker_connections 65535;
}

http {
    server_tokens off;
    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;
    client_max_body_size 1G;

    # SSL Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Recommended security headers
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "no-referrer";

    ##########################
    # REDIRECT HTTP TO HTTPS #
    ##########################
    server {
        listen 80;
        server_name vault.example.com;
        return 301 https://$host$request_uri;
    }

    ##########################
    # VAULT SERVER           #
    ##########################
    server {
        listen 443 ssl;
        server_name vault.example.com;

        ssl_certificate /etc/ssl/certs/certs.pem;
        ssl_certificate_key /etc/ssl/private/private.key;

        # Upstream Vault container
        set $vault_backend vault:8200;

        location / {
            proxy_pass http://$vault_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Ssl on;

            # required to allow long-polling & streaming from UI
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_buffering off;
            proxy_request_buffering off;

            # helpful timeouts
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 300s;
        }
    }
}
